<?php

namespace Database\Seeders;

use Illuminate\Database\Console\Seeds\WithoutModelEvents;
use Illuminate\Database\Seeder;
use App\Models\Product;
class ProductSeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        Product::create([
            'product_name' => 'Taladro1',
            'category_id' => 1,
            'supplier_id' => 1,
            'marca_id'=>1,
            'descripcion'=>"Este taladro es de la reconocida marca y modelo, ofreciendo una excelente calidad y rendimiento. Con su potente motor, es capaz de perforar diversos materiales con facilidad y precisión.",
            'almacen_id'=>1,
            'product_code' => 'CR333',
            'product_garage' => 'Garaje A',
            'product_image' => 'Taladro1.jpg',
            'imagen2' => 'Taladro2.jpg',
            'imagen3' => 'Taladro3.jpg',
            'product_store' => 100,
            'buying_date' => '2024-02-16',
            'expire_date' => '2025-02-16',
            'buying_price' => 100,
            'selling_price' => 150,
            'precio1' => 80,
            'precio2' => 100,
            'precio3' => 200,
            'precio4' => 300,
        ]);

        Product::create([
            'product_name' => 'Taladro2',
            'category_id' => 1,
            'supplier_id' => 1,
            'marca_id'=>2,
            'descripcion'=>"Este taladro es de la reconocida marca y modelo, ofreciendo una excelente calidad y rendimiento. Con su potente motor, es capaz de perforar diversos materiales con facilidad y precisión.",
            'almacen_id'=>1,
            'product_code' => 'CR444',
            'product_garage' => 'Garaje B',
            'product_image' => 'Taladro2.jpg',
            'imagen2' => 'Taladro2.jpg',
            'imagen3' => 'Taladro3.jpg',
            'product_store' => 50,
            'buying_date' => '2024-02-16',
            'expire_date' => '2025-02-16',
            'buying_price' => 100,
            'selling_price' => 150,
            'precio1' => 80,
            'precio2' => 100,
            'precio3' => 200,
            'precio4' => 300,
        ]);
        Product::create([
            'product_name' => 'Taladro3',
            'category_id' => 2,
            'supplier_id' => 1,
            'marca_id'=>2,
            'descripcion'=>"Este taladro es de la reconocida marca y modelo, ofreciendo una excelente calidad y rendimiento. Con su potente motor, es capaz de perforar diversos materiales con facilidad y precisión.",
            'almacen_id'=>1,
            'product_code' => 'CR222',
            'product_garage' => 'Garaje C',
            'product_image' => 'Taladro3.jpg',
            'imagen2' => 'Taladro2.jpg',
            'imagen3' => 'Taladro3.jpg',
            'product_store' => 75,
            'buying_date' => '2024-02-16',
            'expire_date' => '2025-02-16',
            'buying_price' => 100,
            'selling_price' => 150,
            'precio1' => 80,
            'precio2' => 100,
            'precio3' => 200,
            'precio4' => 300,
        ]);
        
        Product::create([
            'product_name' => 'Taladro 4',
            'category_id' => 2,
            'supplier_id' => 1,
            'marca_id'=>1,
            'descripcion'=>"Este taladro es de la reconocida marca y modelo, ofreciendo una excelente calidad y rendimiento. Con su potente motor, es capaz de perforar diversos materiales con facilidad y precisión.",
            'almacen_id'=>1,
            'product_code' => 'CR555',
            'product_garage' => 'Garaje D',
            'product_image' => 'Taladro4.jpg',
            'imagen2' => 'Taladro2.jpg',
            'imagen3' => 'Taladro3.jpg',
            'product_store' => 40,
            'buying_date' => '2024-02-16',
            'expire_date' => '2025-02-16',
            'buying_price' => 100,
            'selling_price' => 150,
            'precio1' => 80,
            'precio2' => 100,
            'precio3' => 200,
            'precio4' => 300,
        ]);
        Product::create([
            'product_name' => 'Taldro 5',
            'category_id' => 1,
            'supplier_id' => 1,
            'marca_id'=>1,
            'descripcion'=>"Este taladro es de la reconocida marca y modelo, ofreciendo una excelente calidad y rendimiento. Con su potente motor, es capaz de perforar diversos materiales con facilidad y precisión.",
            'almacen_id'=>1,
            'product_code' => 'CRPyraminx',
            'product_garage' => 'Garaje E',
            'product_image' => 'Taladro5.jpg',
            'imagen2' => 'Taladro2.jpg',
            'imagen3' => 'Taladro3.jpg',
            'product_store' => 30,
            'buying_date' => '2024-02-16',
            'expire_date' => '2025-02-16',
            'buying_price' => 17.99,
            'selling_price' => 29.99,
            'precio1' => 80,
            'precio2' => 100,
            'precio3' => 200,
            'precio4' => 300,
        ]);
        
        Product::create([
            'product_name' => 'Taldro 6',
            'category_id' => 1,
            'supplier_id' => 1,
            'marca_id'=>1,
            'descripcion'=>"Este taladro es de la reconocida marca y modelo, ofreciendo una excelente calidad y rendimiento. Con su potente motor, es capaz de perforar diversos materiales con facilidad y precisión.",
            'almacen_id'=>1,
            'product_code' => 'CRMirror',
            'product_garage' => 'Garaje F',
            'product_image' => 'Taladro6.jpg',
            'imagen2' => 'Taladro2.jpg',
            'imagen3' => 'Taladro3.jpg',
            'product_store' => 20,
            'buying_date' => '2024-02-16',
            'expire_date' => '2025-02-16',
            'buying_price' => 19.99,
            'selling_price' => 34.99,
            'precio1' => 80,
            'precio2' => 100,
            'precio3' => 200,
            'precio4' => 300,
        ]);
        
        Product::create([
            'product_name' => 'Taldro 7',
            'category_id' => 1,
            'supplier_id' => 1,
            'marca_id'=>1,
            'descripcion'=>"Este taladro es de la reconocida marca y modelo, ofreciendo una excelente calidad y rendimiento. Con su potente motor, es capaz de perforar diversos materiales con facilidad y precisión.",
            'almacen_id'=>1,
            'product_code' => 'CRMegaminx',
            'product_garage' => 'Garaje G',
            'product_image' => 'Taladro7.jpg',
            'imagen2' => 'Taladro2.jpg',
            'imagen3' => 'Taladro3.jpg',
            'product_store' => 25,
            'buying_date' => '2024-02-16',
            'expire_date' => '2025-02-16',
            'buying_price' => 100,
            'selling_price' => 150,
            'precio1' => 80,
            'precio2' => 100,
            'precio3' => 200,
            'precio4' => 300,
        ]);

        Product::create([
            'product_name' => 'Destornillador eléctrico',
            'category_id' => 1,
            'supplier_id' => 3,
            'marca_id'=>2,
            'descripcion'=>"Este destornillador eléctrico es una herramienta indispensable para cualquier hogar o taller. Con su diseño ergonómico y su potente motor, facilita el trabajo de apretar y aflojar tornillos en diferentes superficies. Además, su batería recargable proporciona una gran autonomía.",
            'almacen_id'=>2,
            'product_code' => 'DEl2345',
            'product_garage' => 'Garaje H',
            'product_image' => 'Taladro1.jpg',
            'imagen2' => 'Taladro2.jpg',
            'imagen3' => 'Taladro3.jpg',
            'product_store' => 30,
            'buying_date' => '2024-03-10',
            'expire_date' => '2025-03-10',
            'buying_price' => 80,
            'selling_price' => 120,
            'precio1' => 70,
            'precio2' => 90,
            'precio3' => 150,
            'precio4' => 250,
        ]);
        Product::create([
            'product_name' => 'Sierra circular',
            'category_id' => 1,
            'supplier_id' => 1,
            'marca_id'=>1,
            'descripcion'=>"La sierra circular es una herramienta esencial para realizar cortes precisos en una variedad de materiales, como madera, plástico y metal. Su potente motor y diseño ergonómico la hacen ideal para proyectos de carpintería y construcción.",
            'almacen_id'=>3,
            'product_code' => 'SC234',
            'product_garage' => 'Garaje I',
            'product_image' => 'Taladro1.jpg',
            'imagen2' => 'Taladro2.jpg',
            'imagen3' => 'Taladro3.jpg',
            'product_store' => 15,
            'buying_date' => '2024-04-20',
            'expire_date' => '2025-04-20',
            'buying_price' => 200,
            'selling_price' => 300,
            'precio1' => 180,
            'precio2' => 250,
            'precio3' => 400,
            'precio4' => 500,
        ]);
        
        Product::create([
            'product_name' => 'Cinta métrica',
            'category_id' => 1,
            'supplier_id' => 1,
            'marca_id'=>2,
            'descripcion'=>"La cinta métrica es una herramienta básica pero fundamental en cualquier caja de herramientas. Permite medir longitudes con precisión y facilidad, siendo útil tanto para proyectos de bricolaje como para uso profesional en la construcción.",
            'almacen_id'=>1,
            'product_code' => 'CM56',
            'product_garage' => 'Garaje J',
            'product_image' => 'Taladro1.jpg',
            'imagen2' => 'Taladro2.jpg',
            'imagen3' => 'Taladro3.jpg',
            'product_store' => 50,
            'buying_date' => '2024-05-05',
            'expire_date' => '2025-05-05',
            'buying_price' => 10,
            'selling_price' => 15,
            'precio1' => 8,
            'precio2' => 12,
            'precio3' => 20,
            'precio4' => 25,
        ]);
        
        // Agrega más seeders según sea necesario
        Product::create([
            'product_name' => 'Martillo de carpintero',
            'category_id' => 1,
            'supplier_id' => 1,
            'marca_id'=>1,
            'descripcion'=>"El martillo de carpintero es una herramienta esencial en cualquier taller. Su cabeza de acero endurecido y su mango de madera proporcionan la fuerza y durabilidad necesarias para realizar una amplia variedad de tareas de carpintería.",
            'almacen_id'=>1,
            'product_code' => 'MC123',
            'product_garage' => 'Garaje K',
            'product_image' => 'Taladro1.jpg',
            'imagen2' => 'Taladro2.jpg',
            'imagen3' => 'Taladro3.jpg',
            'product_store' => 20,
            'buying_date' => '2024-06-15',
            'expire_date' => '2025-06-15',
            'buying_price' => 15,
            'selling_price' => 25,
            'precio1' => 12,
            'precio2' => 20,
            'precio3' => 30,
            'precio4' => 40,
        ]);
        
        Product::create([
            'product_name' => 'Llave ajustable',
            'category_id' => 1,
            'supplier_id' => 1,
            'marca_id'=>1,
            'descripcion'=>"La llave ajustable es una herramienta versátil que se utiliza para apretar o aflojar tuercas y pernos de diferentes tamaños. Su diseño ajustable la hace ideal para una amplia gama de aplicaciones en la mecánica, fontanería y otras áreas.",
            'almacen_id'=>1,
            'product_code' => 'LA789',
            'product_garage' => 'Garaje L',
            'product_image' => 'Taladro1.jpg',
            'imagen2' => 'Taladro2.jpg',
            'imagen3' => 'Taladro3.jpg',
            'product_store' => 30,
            'buying_date' => '2024-07-01',
            'expire_date' => '2025-07-01',
            'buying_price' => 20,
            'selling_price' => 30,
            'precio1' => 18,
            'precio2' => 25,
            'precio3' => 40,
            'precio4' => 50,
        ]);
        
        Product::create([
            'product_name' => 'Taladro percutor inalámbrico',
            'category_id' => 1,
            'supplier_id' => 7,
            'marca_id'=>2,
            'descripcion'=>"Este taladro percutor inalámbrico ofrece la máxima libertad de movimiento sin sacrificar la potencia. Con su función de percusión, es ideal para perforar en materiales duros como el hormigón. Su diseño compacto lo hace perfecto para trabajos en espacios reducidos.",
            'almacen_id'=>1,
            'product_code' => 'TP453',
            'product_garage' => 'Garaje M',
            'product_image' => 'Taladro1.jpg',
            'imagen2' => 'Taladro2.jpg',
            'imagen3' => 'Taladro3.jpg',
            'product_store' => 25,
            'buying_date' => '2024-08-10',
            'expire_date' => '2025-08-10',
            'buying_price' => 120,
            'selling_price' => 180,
            'precio1' => 100,
            'precio2' => 150,
            'precio3' => 250,
            'precio4' => 350,
        ]);
        
        Product::create([
            'product_name' => 'Taladro de columna',
            'category_id' => 1,
            'supplier_id' => 1,
            'marca_id'=>1,
            'descripcion'=>"El taladro de columna es una herramienta indispensable para trabajos de precisión en el taller. Su diseño robusto y estable permite perforaciones exactas en diferentes materiales. Es ideal para uso profesional y bricolaje avanzado.",
            'almacen_id'=>2,
            'product_code' => 'TC567',
            'product_garage' => 'Garaje N',
            'product_image' => 'Taladro1.jpg',
            'imagen2' => 'Taladro2.jpg',
            'imagen3' => 'Taladro3.jpg',
            'product_store' => 10,
            'buying_date' => '2024-09-20',
            'expire_date' => '2025-09-20',
            'buying_price' => 300,
            'selling_price' => 450,
            'precio1' => 280,
            'precio2' => 400,
            'precio3' => 600,
            'precio4' => 800,
        ]);
        
        Product::create([
            'product_name' => 'Taladro angular',
            'category_id' => 1,
            'supplier_id' => 1,
            'marca_id'=>1,
            'descripcion'=>"El taladro angular es perfecto para realizar perforaciones en espacios difíciles de alcanzar. Con su diseño compacto y cabezal giratorio, permite trabajar en ángulos estrechos y en lugares de difícil acceso. Es ideal para proyectos de carpintería y montaje de muebles.",
            'almacen_id'=>1,
            'product_code' => 'TA789',
            'product_garage' => 'Garaje O',
            'product_image' => 'Taladro1.jpg',
            'imagen2' => 'Taladro2.jpg',
            'imagen3' => 'Taladro3.jpg',
            'product_store' => 20,
            'buying_date' => '2024-10-05',
            'expire_date' => '2025-10-05',
            'buying_price' => 150,
            'selling_price' => 220,
            'precio1' => 130,
            'precio2' => 200,
            'precio3' => 300,
            'precio4' => 400,
        ]);
        
        Product::create([
            'product_name' => 'Taladro de impacto eléctrico',
            'category_id' => 1,
            'supplier_id' => 1,
            'marca_id'=>1,
            'descripcion'=>"El taladro de impacto eléctrico es una herramienta potente y versátil que combina la acción de perforación con un mecanismo de golpeo. Esto lo hace ideal para perforar en materiales duros como ladrillo, hormigón y piedra. Es imprescindible para trabajos de construcción y renovación.",
            'almacen_id'=>1,
            'product_code' => 'TIE345',
            'product_garage' => 'Garaje P',
            'product_image' => 'Taladro1.jpg',
            'imagen2' => 'Taladro2.jpg',
            'imagen3' => 'Taladro3.jpg',
            'product_store' => 15,
            'buying_date' => '2024-11-15',
            'expire_date' => '2025-11-15',
            'buying_price' => 180,
            'selling_price' => 270,
            'precio1' => 160,
            'precio2' => 240,
            'precio3' => 350,
            'precio4' => 450,
        ]);
        
        Product::create([
            'product_name' => 'Taladro de percusión inalámbrico',
            'category_id' => 1,
            'supplier_id' => 1,
            'marca_id'=>1,
            'descripcion'=>"Este taladro de percusión inalámbrico es perfecto para perforar en una amplia variedad de materiales, desde madera hasta metal y hormigón. Su función de percusión proporciona un rendimiento potente incluso en las superficies más duras. Además, su diseño inalámbrico ofrece total libertad de movimiento.",
            'almacen_id'=>1,
            'product_code' => 'TPI123',
            'product_garage' => 'Garaje Q',
            'product_image' => 'Taladro1.jpg',
            'imagen2' => 'Taladro2.jpg',
            'imagen3' => 'Taladro3.jpg',
            'product_store' => 30,
            'buying_date' => '2024-12-01',
            'expire_date' => '2025-12-01',
            'buying_price' => 250,
            'selling_price' => 380,
            'precio1' => 230,
            'precio2' => 350,
            'precio3' => 500,
            'precio4' => 600,
        ]);
        
        Product::create([
            'product_name' => 'Mini taladro de mano',
            'category_id' => 1,
            'supplier_id' => 1,
            'marca_id'=>1,
            'descripcion'=>"El mini taladro de mano es una herramienta portátil y compacta que permite realizar trabajos de precisión en espacios reducidos. Es ideal para proyectos de artesanía, modelismo y reparaciones delicadas. Su diseño ergonómico facilita un agarre cómodo y controlado.",
            'almacen_id'=>1,
            'product_code' => 'MTM456',
            'product_garage' => 'Garaje R',
            'product_image' => 'Taladro1.jpg',
            'imagen2' => 'Taladro2.jpg',
            'imagen3' => 'Taladro3.jpg',
            'product_store' => 40,
            'buying_date' => '2025-01-10',
            'expire_date' => '2026-01-10',
            'buying_price' => 50,
            'selling_price' => 80,
            'precio1' => 45,
            'precio2' => 70,
            'precio3' => 100,
            'precio4' => 120,
        ]);
        
        
        
    }
}
